# Generated by Django 5.1.1 on 2024-10-17 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='team',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='invitation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 17, 5, 49, 6, 71843, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
