# Generated by Django 5.1.1 on 2024-10-17 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_alter_team_teamleader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Notifaction',
            fields=[
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('invite_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('INVITATION', 'Invitation'), ('NEW_PROJECT', 'New Project'), ('NEW_REPORT', 'New Report'), ('ALART', 'Alart')], max_length=20, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('other_data', models.JSONField(blank=True, null=True)),
                ('other_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
