# Generated by Django 5.1.1 on 2024-10-18 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_project_created_at_project_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supervisor_choices',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'faculty'}, related_name='supervisor_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
