# Generated by Django 5.1.1 on 2024-10-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_alter_project_supervisor_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='studentname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
